name: Run tests with coverage

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x

      - name: Download
        run: go mod download

      - name: Test
        run: go test -v -cover ./...